### ISSUE TITLE
Global variables and classes

### ISSUE THREAD

**Issue by isabellaalstrom** [helto4real/netdaemon#4]
Use of global classes for variables and methods that can be shared between all apps.
Make GetState() and other helper methods for hass available in these classes, and dont require yaml file.

**Comment by helto4real** [comment]
Global classes can now be used as of #7.  As for implementing GetState and the other methods the only viable solution is to inject  the INetDaemon if provided as constructor as an solution for those classes. I will have to think about the design. Can you give example of use-case and how it will be used?

**Comment by helto4real** [comment]
Closing it casue most is implemented
